version: '2'
services:
  sdk-file-nginx:
    image: nginx
    restart: always
    ports:
      - "6060:6060"
    volumes:
      - /nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/html/:/data/nginx/html/
    environment:
      - TZ=Asia/Shanghai
    networks:
      - sdk

networks:
  sdk:
    driver: bridge
